/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#b41340",
        "surface-container": "#e9e5ff",
        "inverse-on-surface": "#9c98c6",
        "inverse-primary": "#7387ff",
        "secondary-container": "#45fec9",
        "error-container": "#f74b6d",
        "surface-dim": "#d4cfff",
        "secondary-fixed": "#45fec9",
        "inverse-surface": "#0b082f",
        "on-tertiary-fixed": "#360600",
        "on-tertiary": "#ffefec",
        "tertiary-fixed": "#ff9479",
        "secondary-fixed-dim": "#2cefbc",
        "surface-container-highest": "#ddd9ff",
        "background": "#f9f5ff",
        "on-surface-variant": "#5a5781",
        "on-primary": "#f3f1ff",
        "surface-variant": "#ddd9ff",
        "surface-bright": "#f9f5ff",
        "outline": "#75729e",
        "primary-dim": "#0934e0",
        "on-tertiary-container": "#621200",
        "tertiary": "#af2700",
        "outline-variant": "#aca8d7",
        "tertiary-container": "#ff9479",
        "on-secondary-fixed-variant": "#006850",
        "primary": "#2444eb",
        "on-background": "#2c2a51",
        "primary-container": "#8999ff",
        "on-secondary": "#c6ffe7",
        "tertiary-fixed-dim": "#ff7d5c",
        "tertiary-dim": "#9a2100",
        "on-surface": "#2c2a51",
        "on-primary-fixed-variant": "#001a88",
        "surface-container-low": "#f3eeff",
        "on-secondary-fixed": "#004937",
        "surface-container-high": "#e3dfff",
        "on-error": "#ffefef",
        "on-secondary-container": "#005d47",
        "primary-fixed-dim": "#778aff",
        "secondary-dim": "#005b45",
        "on-tertiary-fixed-variant": "#721600",
        "secondary": "#006850",
        "on-primary-container": "#001470",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#000000",
        "primary-fixed": "#8999ff",
        "surface": "#f9f5ff",
        "on-error-container": "#510017",
        "error-dim": "#a70138",
        "surface-tint": "#2444eb"
      },
      fontFamily: {
        "headline": ["Outfit", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" }
    },
  },
  plugins: [],
}

